### ISSUE TITLE
Support for multiple Google accounts

### ISSUE THREAD

**Issue by mu88** [whyorean/AuroraStore#1]
Hi,
Do you have plans to add support for multiple Google accounts? For example, I have a German and a Swiss Google account to buy apps in both countries. However, within Aurora, I always have to switch logins for getting updates.

**Comment by DarkCrypt** [comment]
This is a mirror repo, I wouldn't expect a response from the dev.

**OFFICIAL REPO ->** GitLab: [Aurora Store - Official Repo](https://gitlab.com/AuroraOSS/AuroraStore)

You can login at GitLab with your GitHub account.

**Comment by mu88** [comment]
See https://gitlab.com/AuroraOSS/AuroraStore/-/issues/495
