### ISSUE TITLE
Add battlegrounds mobile india app to the appstore

### ISSUE THREAD

**Issue by prorounak2005** [whyorean/AuroraStore#10]
Battlegrounds mobile india is a game made by krafton corporation after the indan government banned pubg mobile in India which was managed by tencent. Krafton made a new game only for India which is battlegrounds mobile india. It is there on playstore but it is not there on the aurora app store when u log in anonymously. 
Battlegrounds mobile india apk link - https://www.apkmirror.com/apk/krafton-inc/battlegrounds-mobile-india/battlegrounds-mobile-india-1-7-0-release/

**Comment by saurabhinabys** [comment]
do you even understand the purpose of the app?It's not a custom repo, it just pulls apps from play store. availability of apps is dependent on the google account's location and settings.

**Comment by prorounak2005** [comment]
nvm thanks btw. Closing the issue.
