### ISSUE TITLE
Aurora Store- Protocol Error: Stream was reset

### ISSUE THREAD

**Issue by AA-Coder-Beg** [whyorean/AuroraStore#17]
When I attempted to sign in anonymously to Aurora Store, I was met with the protocol error. 

When I signed out, I was still met with the error. 

![Screenshot_20220817-233722](https://user-images.githubusercontent.com/82636431/185295102-95402faa-9e0a-496b-8266-5c818570c9e6.png)

**Comment by Kromzem** [comment]
I don't know exactly whats different with these version, but it seems that the latest nightly release is working well:
https://files.auroraoss.com/AuroraStore/Nightly/

**Comment by ceselder** [comment]
I can reproduce

**Comment by Disqu3-mirOir-qt** [comment]
now problem it,s fixed

**Comment by AA-Coder-Beg** [comment]
Howdy! So, I have no idea what happened, but the error has since been resolved. I'm not sure how it just resolved itself, so I'll leave this open for anyone else who still has this issue

**Comment by AA-Coder-Beg** [comment]
Closing now. No explanations given after months

**Comment by ShareASmile** [comment]
"Stream was reset  "Protocol Error" problem is back again today on 12Dec 2022, i think token dispenser is  down again as it was case months ago, this is 3-4 times this has happened can't login anonymous but anonymous (insecure login) worked for me as was suggested in a reddit post months ago

**Comment by Disqu3-mirOir-qt** [comment]
![Screenshot_20221212-165642_1.jpg](https://user-images.githubusercontent.com/41585567/207092169-801d5c33-8f26-41c1-8157-6cd572bf67bc.jpg)

**Comment by ShareASmile** [comment]
Login issue was solved on 12Dec later in the day.
Thanks btw
