### ISSUE TITLE
Game(s) won't load- Google Play Error?

### ISSUE THREAD

**Issue by AA-Coder-Beg** [whyorean/AuroraStore#26]
I have installed a game through Aurora, but when I try to play it, I recieved the following error message:

![Screenshot_20221127-222940](https://user-images.githubusercontent.com/82636431/204194425-51d56669-71d4-4000-844f-042740e22009.png)

This happened to me with another game as well. The game I took this screenshot of is called Maze: Path of Light. The other game that had this issue is called Egg, Inc. 

I had updated my Google Play, so I'm not sure why it's still throwing this message.

Edit: Before anyone says anything (if at all...), I have updated my Google Play Services to the latest version

**Comment by AA-Coder-Beg** [comment]
Problem is still not resolved...

**Comment by puppetmasterr** [comment]
Could you provide some more info about your device, OS and their versions?

**Comment by DarkCrypt** [comment]
This is a mirror repo, I wouldn't expect a response from the dev.

**OFFICIAL REPO ->** GitLab: [Aurora Store - Official Repo](https://gitlab.com/AuroraOSS/AuroraStore)

You can login at GitLab with your GitHub account.
