### ISSUE TITLE
Allow creation of reviews.

### ISSUE THREAD

**Issue by rokejulianlockhart** [whyorean/AuroraStore#29]
Currently, I appear solely able to review applications with stars – I am unable to add text to accompany it, despite the Play Store allowing this.

**Comment by DarkCrypt** [comment]
This is a mirror repo, I wouldn't expect a response from the dev.

**OFFICIAL REPO ->** GitLab: [Aurora Store - Official Repo](https://gitlab.com/AuroraOSS/AuroraStore)

You can login at GitLab with your GitHub account.
