### ISSUE TITLE
Previously posted reviews do not load when visiting the page of an application.

### ISSUE THREAD

**Issue by rokejulianlockhart** [whyorean/AuroraStore#30]
My previously posted reviews appear to not load when I visit the page of an application. Consequently, I worry that accidentally posting (or changing?) stars as a review shall overwrite what I have posted via the Play Store.

**Comment by DarkCrypt** [comment]
This is a mirror repo, I wouldn't expect a response from the dev.

**OFFICIAL REPO ->** GitLab: [Aurora Store - Official Repo](https://gitlab.com/AuroraOSS/AuroraStore)

You can login at GitLab with your GitHub account.

**Comment by rokejulianlockhart** [comment]
https://gitlab.com/AuroraOSS/AuroraStore/-/issues/737#note_1425853540
