### ISSUE TITLE
Aurora Store crashes on the latest version of the app

### ISSUE THREAD

**Issue by kirk781** [whyorean/AuroraStore#34]
The previous version had some bugs for me like it didn't show some apps properly on the front page, but by and large, it handled searching and updating installed apps properly. The newly released version just crashes for me on first launch only. I tried it on Android 12. The previous version still works okay for me.

I have an Android 13 phone as well. I am not sure if I tested the latest version on that phone. Eithercase, the previous versions ran decently on both phones.

**Comment by ProPatte** [comment]
Refer to https://github.com/whyorean/AuroraStore/issues/33
