### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by timedin-de** [whyorean/AuroraStore#37]
Add the option to proxy google request.
For privacy reasons i block every dns request belonging to google. So it would be nice to use a proxy to download apps and info.

**Comment by DarkCrypt** [comment]
This is a mirror repo, I wouldn't expect a response from the dev.

**OFFICIAL REPO ->** GitLab: [Aurora Store - Official Repo](https://gitlab.com/AuroraOSS/AuroraStore)

You can login at GitLab with your GitHub account.
