### ISSUE TITLE
Better clarify in README.md that source code is being actively developed on Gitlab

### ISSUE THREAD

**Issue by jahway603** [whyorean/AuroraStore#41]
Better clarify in README.md that source code is being actively developed on Gitlab by updating the README.md with clear language about this and then archiving this repo.

**Comment by DarkCrypt** [comment]
I wouldn't expect a response from dev.

**OFFICIAL REPO** at GitLab: [Aurora Store - Official](https://gitlab.com/AuroraOSS/AuroraStore)
